### ISSUE TITLE
怎么设置多行看板？

### ISSUE THREAD

**Issue by qiyueliuhuo** [benjypng/logseq-kanban-plugin#16]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/15904121/163696271-2c707dd6-14cb-46c5-af8f-3b4b27e26b22.png">
比如这个形成多行

**Comment by qiyueliuhuo** [comment]
![image](https://user-images.githubusercontent.com/15904121/164714855-b088803b-017b-48b5-a6f9-4ed668741e6a.png)
像上面这样，当添加的内容太多时，显示不全，需要拖动鼠标滚轮/或者滚动才能查看后面的内容，我想要的效果是可以换行显示，折叠到下面，形成多行，这样就能直接显示出来，不用拖动/滚动，显示后面的内容，谢谢你的回答！
当然，好像可以通过创建多个/kanban 的指令来达到多行显示效果，但是总觉得不够优雅。

**Comment by hkgnp** [comment]
I see. I can try to see if some adjustments can be done.

**Comment by qiyueliuhuo** [comment]
> I see. I can try to see if some adjustments can be done.

谢谢

**Comment by benjypng** [comment]
Was thinking about it and decided that multi-line kanban probably doesn't make sense as a kanban board.
