### ISSUE TITLE
Enlarge Images

### ISSUE THREAD

**Issue by r96941046** [benjypng/logseq-kanban-plugin#18]
There are enlarge buttons when cursors hover over images in Logseq; however, no enlarge button is given when using images with this kanban plugin. The only way to enlarge the image is by going into the data. Can we somehow enlarge images with this plugin? Thank you.

**Comment by hkgnp** [comment]
Hi, I am actually not hooking onto the way Logseq renders images, and am just rendering the image in HTML. 
Hence, will require some time to make it like such. Will be happy to keep this FR up, in case anyone wants to do a PR.

**Comment by benjypng** [comment]
Closed as stale.
