### ISSUE TITLE
Ability to publish rendered Kanban

### ISSUE THREAD

**Issue by jesselang** [benjypng/logseq-kanban-plugin#26]
Hello. I really like the concept of this plugin. One thing I currently do is export HTML and copy/paste into Confluence. Is there a way to export the rendering of this plugin in that HTML export? Or any other publishing abilities? Thanks!

**Comment by benjypng** [comment]
Can try in the latest version. You can right click on the block that contains the kanban, and select the option `Copy Kanban HTML`.
