### ISSUE TITLE
query error

### ISSUE THREAD

**Issue by electriquo** [benjypng/logseq-kanban-plugin#35]
when trying to collect all my tasks into a kanban board using a query as stated in https://github.com/hkgnp/logseq-kanban-plugin#query-tasks, i get an error

![image](https://github.com/hkgnp/logseq-kanban-plugin/assets/28758375/ecdeebc1-dedb-4f55-81b4-06e07566f7d5)

![image](https://github.com/hkgnp/logseq-kanban-plugin/assets/28758375/9de29cf7-6f09-45fb-9a5e-07fcedd3b5ea)

any idea how to fix the error?

**Comment by hkgnp** [comment]
This should be fixed in the latest version.

**Comment by hkgnp** [comment]
You can try the latest release.
