### ISSUE TITLE
Work with page qeury?

### ISSUE THREAD

**Issue by shinglyu** [benjypng/logseq-kanban-plugin#36]
I use Normal with Query, but if I have a query that gets pages (e.g. `{{query (page-tags project)}}`), the cards are empty. it would be great if we can use the page title as the card title.

**Comment by hkgnp** [comment]
Hmm sorry I am not sure I understand what you mean. What does that query return in your example?

**Comment by MNandor** [comment]
I'm here for the same reason:

Logseq has Pages (one .md file) and Blocks (one line and whatever's indented underneath it).

The plugin works great with queries returning Blocks. Block contents show up in the Kanban view.

However, with queries returning Pages, the title of the Page is not displayed. Instead we get an empty white box.

**Comment by benjypng** [comment]
Fixed in latest version.
