### ISSUE TITLE
Render SCHEDULED and DEADLINE

### ISSUE THREAD

**Issue by akippnn** [benjypng/logseq-kanban-plugin#37]
This is how it looks like in Logseq:
![image](https://github.com/hkgnp/logseq-kanban-plugin/assets/80670461/4572794c-b547-4a46-b04c-70d7190d4451)

This is how it looks like in the Kanban Plugin:
![image](https://github.com/hkgnp/logseq-kanban-plugin/assets/80670461/ba306191-9591-4904-aac8-5f5506bf580f)

**Comment by benjypng** [comment]
Fixed in latest version.
