### ISSUE TITLE
Can't drag to empty column

### ISSUE THREAD

**Issue by CptTwinkie** [benjypng/logseq-kanban-plugin#40]
v3.6.2
After I updated there is no longer a target in the empty column to drop onto

**Comment by benjypng** [comment]
Can't seem to replicate.

https://github.com/user-attachments/assets/ba304ec7-3a2d-4e06-8509-32ae67651e36

**Comment by CptTwinkie** [comment]
I can confirm I'm no longer having the issue. Maybe it was being caused by another plugin. A few of them have updated lately. Thanks for looking at it.
