### ISSUE TITLE
why query-tasks doesn't work?

### ISSUE THREAD

**Issue by Morganwan90** [benjypng/logseq-kanban-plugin#42]
hello, the plugin you've developed is exactly what I need!
I have just started using Logseq... there might be some mistakes in my operation.
I tried to use query-tasks on the board following the instructions in the README.

<img width="464" alt="截图_20240721000915" src="https://github.com/user-attachments/assets/0be1ab13-6449-4f88-b6df-9c9b12f34f58">

It correctly displays the results, but it does not render them properly into a Kanban board. Is there an issue with the way I'm using it?

<img width="640" alt="截图_20240721001038" src="https://github.com/user-attachments/assets/eb4be52e-b409-4ae0-acae-06cb9a5ddad0">

**Comment by bunnyhero** [comment]
it stopped working for me too

**Comment by benjypng** [comment]
Fixed in latest version.
